# Generated by Django 3.2.18 on 2023-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('posicao', models.CharField(max_length=30)),
                ('peDominante', models.CharField(max_length=30)),
                ('nacionalidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=30)),
                ('codigo_time', models.CharField(max_length=10)),
                ('fundacao', models.DateField()),
                ('titulos', models.CharField(max_length=30)),
            ],
        ),
    ]
