# Generated by Django 3.2.18 on 2023-02-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.jogador')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogadores.time')),
            ],
        ),
    ]
